title: Daniel Masterson
description: Associate Professor, Department of Political Science, University of California, Santa Barbara

url: "https://danielmasterson.github.io"
baseurl: ""

markdown: kramdown
timezone: America/Los_Angeles

include:
  - files

exclude:
  - README.md
  - CHANGELOG.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - package.json
  - node_modules
  - vendor
